version: '3.8'

services:
  app:
    build: app
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app_network
      - immich_default
    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:17
    container_name: postgres_db_immich
    env_file:
      - .env
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data  # Volume для хранения данных PostgreSQL
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  immich_default:
    external: true
  app_network:
    driver: bridge